set -u

PROGRAM=${0##*/}
WORKBRANCH_VERSION=${WORKBRANCH_VERSION:-"0.0.0-dev"}
PROJECT_ROOT=""
CONFIG_FILE=""
CONFIG_TYPE=""
PROJECT_NAME=""
BASE_DIR=""
BRANCH_PREFIX=""
TASK_SETUP=""
IDE_COMMAND=""
TERMINAL_COMMAND=""
REPO_NAMES=()
REPO_URLS=()
REPO_BASE_BRANCHES=()
REPO_SETUP_COMMANDS=()
CREATED_PATHS=()
CREATED_WORKTREES=()
CREATED_WORKTREE_BASES=()
CREATED_BRANCH_REPOS=()
CREATED_BRANCH_NAMES=()
TASK_BRANCH_REPOS=()
TASK_BRANCH_NAMES=()
PREFLIGHT_ERRORS=()
FILTER_REPO=""
ARGS=()
