task_state_dir_path() { printf '%s/%s/.workbranch' "$PROJECT_ROOT" "$1"; }
task_agents_path() { printf '%s/%s/AGENTS.md' "$PROJECT_ROOT" "$1"; }
task_noti_path() { printf '%s/notifications.jsonl' "$(task_state_dir_path "$1")"; }

write_task_agent_guidance() {
  local task file
  task=$1
  file=$(task_agents_path "$task")
  [ -e "$file" ] && return 0
  if [ "${PREFERRED_LANGUAGE:-en}" = "ko" ]; then
    cat > "$file" <<'EOF_GUIDANCE'
# Workbranch 작업 안내

이 파일은 workbranch가 이 task workspace에 생성한 안내입니다.

- AI agent session은 기본적으로 task root(`<task>`)에서 실행합니다.
- task root는 Git repository가 아닙니다. workbranch metadata/agent 작업 공간입니다.
- 실제 Git repo는 `<task>/<repo>` 아래에 있습니다.
- repo를 수정하기 전에 해당 repo 안의 `AGENTS.md`, `CLAUDE.md`, `.claude/` 같은 repo-local agent 지침을 찾아 읽고 따릅니다.

EOF_GUIDANCE
  else
    cat > "$file" <<'EOF_GUIDANCE'
# Workbranch Task Guidance

This file is generated by workbranch for this task workspace.

- Run AI agent sessions from the task root (`<task>`) by default.
- The task root is not a Git repository; it is a workbranch metadata/agent workspace.
- The actual Git repositories live under `<task>/<repo>`.
- Before editing a repo, read and follow repo-local agent instructions such as `<task>/<repo>/AGENTS.md`, `<task>/<repo>/CLAUDE.md`, or `<task>/<repo>/.claude/` when present.

EOF_GUIDANCE
  fi
}

write_default_task_state() {
  local task state_dir
  task=$1
  write_task_agent_guidance "$task" || die "failed to write task agent guidance: $task"
  state_dir=$(task_state_dir_path "$task")
  mkdir -p "$state_dir" || die "failed to initialize task metadata: $task"
  touch "$(task_noti_path "$task")"
}

remove_task_state_files() {
  local task
  task=$1
  rm -f "$(task_agents_path "$task")" "$PROJECT_ROOT/$task/TASK-WORKBRANCH.md"
  rm -rf "$(task_state_dir_path "$task")"
}

resolve_current_task_from_cwd() {
  local dir parent task
  dir=$(pwd -P)
  while [ "$dir" != "$PROJECT_ROOT" ] && [ "$dir" != "/" ]; do
    parent=$(dirname "$dir")
    if [ "$parent" = "$PROJECT_ROOT" ]; then
      task=${dir##*/}
      is_task_workspace_path "$PROJECT_ROOT/$task" || return 1
      printf '%s' "$task"
      return 0
    fi
    dir=$parent
  done
  return 1
}

require_known_task_workspace() {
  local operation task task_dir
  operation=$1
  task=$2
  validate_task_folder_name "$task"
  task_dir="$PROJECT_ROOT/$task"
  if ! is_task_workspace_path "$task_dir"; then
    die "Cannot $operation: unknown task '$task'"
  fi
}

json_string() {
  printf '"'
  printf '%s' "$1" | json_escape
  printf '"'
}

json_escape() {
  awk 'BEGIN {
      ORS = ""
      for (i = 0; i < 32; i++) {
        c = sprintf("%c", i)
        control_escape[c] = sprintf("\\u%04x", i)
      }
      control_escape[sprintf("%c", 8)] = "\\b"
      control_escape[sprintf("%c", 9)] = "\\t"
      control_escape[sprintf("%c", 10)] = "\\n"
      control_escape[sprintf("%c", 12)] = "\\f"
      control_escape[sprintf("%c", 13)] = "\\r"
    }
    {
      if (NR > 1) printf "\\n"
      for (i = 1; i <= length($0); i++) {
        c = substr($0, i, 1)
        if (c == "\\") printf "\\\\"
        else if (c == "\"") printf "\\\""
        else if (c in control_escape) printf "%s", control_escape[c]
        else printf "%s", c
      }
    }'
}

json_unescape() {
  awk '
  function hex_value(c) {
    if (c >= "0" && c <= "9") return c + 0
    c = tolower(c)
    if (c >= "a" && c <= "f") return index("abcdef", c) + 9
    return -1
  }
  function hex_byte(value, hi, lo) {
    hi = hex_value(substr(value, 1, 1))
    lo = hex_value(substr(value, 2, 1))
    if (hi < 0 || lo < 0) return -1
    return hi * 16 + lo
  }
  {
    out = ""
    for (i = 1; i <= length($0); i++) {
      c = substr($0, i, 1)
      if (c == "\\") {
        i++
        e = substr($0, i, 1)
        if (e == "n") out = out "\n"
        else if (e == "t") out = out "\t"
        else if (e == "r") out = out "\r"
        else if (e == "b") out = out sprintf("%c", 8)
        else if (e == "f") out = out sprintf("%c", 12)
        else if (e == "u" && substr($0, i + 1, 2) == "00") {
          code = hex_byte(substr($0, i + 3, 2))
          if (code >= 0 && code < 32) {
            out = out sprintf("%c", code)
            i += 4
          } else {
            out = out e
          }
        }
        else out = out e
      } else {
        out = out c
      }
    }
    print out
  }'
}

noti_count() {
  local file count
  file=$(task_noti_path "$1")
  [ -f "$file" ] || { printf '0'; return 0; }
  count=$(wc -l < "$file" | tr -d '[:space:]')
  printf '%s' "${count:-0}"
}
