#!/usr/bin/env bash
set -u

SCRIPT_DIR=$(cd "$(dirname "$0")" && pwd -P)
REPO_ROOT=$(cd "$SCRIPT_DIR/.." && pwd -P)
WORKBRANCH="$REPO_ROOT/bin/workbranch"

. "$SCRIPT_DIR/lib/helpers.sh"
cases=("$SCRIPT_DIR"/cases/*.sh)
if [ "${#cases[@]}" -eq 0 ] || [ "${cases[0]}" = "$SCRIPT_DIR/cases/*.sh" ]; then
  printf '%s\n' "[-] Error: no test case files found: $SCRIPT_DIR/cases/*.sh" >&2
  exit 1
fi
for case_file in "${cases[@]}"; do
  if [ ! -f "$case_file" ] || [ ! -r "$case_file" ]; then
    printf '%s\n' "[-] Error: invalid test case file: $case_file" >&2
    exit 1
  fi
  if ! . "$case_file"; then
    printf '%s\n' "[-] Error: failed to source test case file: $case_file" >&2
    exit 1
  fi
done

main() {
  [ -x "$WORKBRANCH" ] || fail "missing executable: $WORKBRANCH"
  git --version >/dev/null || fail "git is required"

  run_test test_generated_workbranch_is_up_to_date
  run_test test_run_test_output_uses_status_prefixes
  run_test test_run_expect_helpers_do_not_leak_tty_stdin
  run_test test_run_expect_helpers_preserve_piped_stdin
  run_test test_fail_helper_uses_error_prefix
  run_test test_run_test_continues_after_fail_helper
  run_test test_runner_fails_fast_when_no_case_files
  run_test test_runner_rejects_non_regular_case_file
  run_test test_runner_reports_failed_case_source
  run_test test_help_groups_commands
  run_test test_display_default_error_output_has_no_ansi
  run_test test_display_forced_color_colors_error_prefix
  run_test test_display_no_color_overrides_forced_color
  run_test test_display_auto_redirected_stderr_has_no_ansi
  run_test test_display_color_never_disables_color
  run_test test_display_forced_color_help_shows_banner_and_sections
  run_test test_display_forced_color_help_dims_git_legends
  run_test test_display_no_color_suppresses_enhanced_help
  run_test test_display_forced_color_status_uses_sections_and_colored_states
  run_test test_display_auto_tty_status_preserves_table_colors
  run_test test_display_forced_color_list_uses_repo_and_branch_colors
  run_test test_display_forced_color_add_log_uses_repo_and_branch_colors
  run_test test_display_forced_color_push_log_uses_repo_and_branch_colors
  run_test test_display_forced_color_land_log_uses_repo_and_branch_colors
  run_test test_display_forced_color_init_shows_banner_and_sections
  run_test test_display_forced_color_preflight_guidance_is_colored
  run_test test_display_forced_color_task_setup_failure_is_colored
  run_test test_version_reports_release_manifest_version
  run_test test_help_and_version_work_on_unsupported_platform
  run_test test_core_commands_reject_unsupported_platform
  run_test test_core_commands_allow_linux_and_wsl
  run_test test_complete_helpers_list_tasks_repos_and_commands
  run_test test_complete_helpers_are_silent_outside_project
  run_test test_completion_bash_emits_complete_directive
  run_test test_completion_zsh_emits_compdef
  run_test test_completion_requires_known_shell
  run_test test_completion_bash_completes_tasks_and_repos
  run_test test_completion_bash_uses_command_specific_flags
  run_test test_completion_fish_emits_complete_command
  run_test test_completion_fish_completes_partial_subcommands
  run_test test_completion_fish_uses_long_option_condition_for_repo_values
  run_test test_safe_names_reject_dot_and_dotdot
  run_test test_invalid_config_rejected_without_execution
  run_test test_init_existing_config_clones_base_repos
  run_test test_init_completes_partial_base_clones
  run_test test_init_rejects_existing_base_repo_on_wrong_branch_during_recovery
  run_test test_init_validates_existing_base_repos_before_cloning_missing_repos
  run_test test_init_rejects_existing_base_repo_rebase_in_progress_during_recovery
  run_test test_init_rejects_already_initialized_workbranch_project
  run_test test_init_from_project_subdir_uses_parent_config
  run_test test_init_rejects_existing_non_git_base_target
  run_test test_init_rejects_existing_non_directory_base_target
  run_test test_failed_init_rolls_back_command_created_base_paths
  run_test test_failed_init_reports_git_clone_reason
  run_test test_full_git_flow
  run_test test_update_all_updates_every_task_workspace
  run_test test_update_accepts_gitfile_base_worktree
  run_test test_update_preflight_blocks_batch_before_changes
  run_test test_update_preflight_requires_base_worktree_on_configured_branch
  run_test test_update_preflight_blocks_base_rebase_in_progress
  run_test test_update_preflight_blocks_rebase_conflict_without_touching_task
  run_test test_refresh_pulls_base_then_updates_tasks
  run_test test_refresh_repo_scope_limits_pull_and_update
  run_test test_refresh_repo_scope_collects_tasks_with_only_selected_repo_healthy
  run_test test_refresh_task_pulls_base_then_updates_one_task
  run_test test_refresh_no_tasks_fails_before_pull
  run_test test_refresh_update_preflight_failure_blocks_pull
  run_test test_refresh_task_update_preflight_failure_blocks_pull
  run_test test_refresh_preflight_blocks_rebase_conflict_after_pull_without_touching_task
  run_test test_sync_command_is_removed
  run_test test_doctor_healthy_project_exits_zero
  run_test test_doctor_detects_partial_workspace
  run_test test_doctor_repo_scope_ignores_filtered_out_task_damage
  run_test test_doctor_repo_scope_ignores_stale_dir_with_only_filtered_out_repo
  run_test test_doctor_reports_registered_task_worktree_on_wrong_branch
  run_test test_doctor_reports_base_branch_drift
  run_test test_doctor_reports_stale_directory_with_remove_hint
  run_test test_doctor_rejects_unexpected_args_and_flags
  run_test test_doctor_fix_prunes_stale_worktree_registration
  run_test test_doctor_fix_does_not_delete_stale_task_directory
  run_test test_repo_scope_limits_git_commands_to_one_repo
  run_test test_land_preflight_blocks_all_repos_before_partial_land
  run_test test_finalize_pulls_updates_and_lands_without_push_or_remove
  run_test test_finalize_preflight_blocks_pull_before_dirty_task_update
  run_test test_finalize_preflight_blocks_rebase_conflict_after_pull_without_touching_task
  run_test test_push_supports_task_and_base_branches_after_fast_forward_merge
  run_test test_add_uses_feat_parent_branch_as_default
  run_test test_add_derives_branch_from_conventional_task_folder
  run_test test_add_derives_conventional_branch_from_parent_feature_base
  run_test test_add_prompts_for_task_type_and_detail_without_task_argument
  run_test test_add_task_argument_prefills_interactive_task_detail
  run_test test_add_without_task_argument_supports_from_ref
  run_test test_add_explicit_task_without_conventional_prefix_keeps_legacy_default
  run_test test_add_rejects_legacy_plus_task_folder
  run_test test_add_rejects_conventional_detail_that_builds_invalid_branch
  run_test test_add_rejects_empty_from_equals
  run_test test_add_from_remote_ref_seeds_task_branch_from_origin_ref
  run_test test_add_from_missing_ref_fails_before_creating_task
  run_test test_add_task_branch_override_is_used_by_later_commands
  run_test test_add_rejects_existing_task_branch
  run_test test_add_rejects_remote_only_task_branch_without_remove_advice
  run_test test_add_rejects_invalid_task_branch_override
  run_test test_resume_command_is_removed
  run_test test_remove_deletes_overridden_task_branches
  run_test test_remove_accepts_completion_trailing_slash_for_task_key
  run_test test_remove_deletes_overridden_task_branches_when_task_dir_missing
  run_test test_list_shows_overridden_task_branches
  run_test test_list_shows_conventional_task_folder_and_branch
  run_test test_remove_deletes_task_branch_when_worktree_missing
  run_test test_remove_force_discards_dirty_task
  run_test test_remove_rejects_unmerged_task_branch_without_force
  run_test test_remove_rejects_task_repo_on_unexpected_branch
  run_test test_remove_rejects_missing_base_repo_before_partial_cleanup
  run_test test_remove_force_rejects_missing_base_repo_before_partial_cleanup
  run_test test_add_rolls_back_branch_when_new_worktree_helper_fails
  run_test test_add_rolls_back_dirty_worktree_registration
  run_test test_add_branches_from_local_base_after_land_before_push
  run_test test_status_reports_base_remote_diff_and_next_action
  run_test test_status_reports_base_task_diff_and_worktree_state
  run_test test_status_repo_filter_skips_tasks_without_matching_rows
  run_test test_status_reports_stale_task_shaped_directories_separately
  run_test test_status_reports_standalone_repo_task_dirs_as_stale
  run_test test_status_skips_partial_task_workspaces
  run_test test_path_prints_task_and_repo_paths
  run_test test_path_accepts_completion_trailing_slash_for_task_key
  run_test test_scoped_tool_paths_reject_stale_task_directories
  run_test test_ide_and_terminal_run_configured_command_for_task_repos
  run_test test_ide_legacy_macos_app_preset_opens_new_instance_per_repo
  run_test test_finder_opens_task_root_without_repo_filter
  run_test test_finder_repo_filter_opens_one_repo_path
  run_test test_tool_app_commands_are_macos_only
  run_test test_tool_launcher_forced_color_highlights_tool_and_target_path
  run_test test_tool_commands_require_configured_command
  run_test test_tool_launcher_reports_missing_task_repo_before_running_command
  run_test test_dirty_worktree_safety
  run_test test_remove_reports_kept_task_directory_with_extra_files
  run_test test_remove_treats_missing_worktree_as_already_removed
  run_test test_remove_cleans_stale_task_directory
  run_test test_remove_continues_after_worktree_remove_failure
  run_test test_prune_removes_only_fully_merged_tasks
  run_test test_prune_skips_dirty_merged_task
  run_test test_prune_reports_partial_and_stale_task_skips
  run_test test_prune_returns_failure_after_remove_failure_and_continues
  run_test test_pull_preflight_requires_base_worktree_on_configured_branch
  run_test test_add_preflight_requires_clean_base_on_configured_branch
  run_test test_config_reads_and_writes_ide_terminal_commands
  run_test test_config_ide_can_set_custom_command_without_prompting_repos
  run_test test_config_ide_preset_uses_superset_level1_order
  run_test test_config_tool_preset_names_are_colored
  run_test test_config_terminal_can_clear_without_removing_ide
  run_test test_config_tool_targets_are_macos_only
  run_test test_config_base_checks_out_changed_base_branches_before_add
  run_test test_config_base_preflights_fast_forward_before_checkout
  run_test test_config_base_pulls_when_branch_already_checked_out
  run_test test_full_config_skips_tool_prompts_on_linux
  run_test test_full_config_repo_setup_change_does_not_touch_unchanged_dirty_base
  run_test test_full_config_base_branch_change_auto_applies_without_stale_manual_guidance
  run_test test_config_writes_config_without_cloning
  run_test test_config_rewrites_legacy_config_without_cloning
  run_test test_config_keeps_glob_characters_literal
  run_test test_init_accepts_legacy_config_without_rewrite
  run_test test_legacy_config_supports_project_commands_without_rewrite
  run_test test_config_rewrites_legacy_tasktree_config_without_cloning
  run_test test_task_setup_can_be_configured_and_run
  run_test test_setup_command_is_removed
  run_test test_config_preserves_task_setup_while_prompting_repo_setup
  run_test test_config_preserves_existing_branch_prefix_without_prompting
  run_test test_config_rejects_main_worktrees_dir_change_when_base_worktrees_exist
  run_test test_config_base_checks_out_configured_base_branch_for_cloned_repo
  run_test test_repo_setup_can_be_configured_and_run_per_repo
  run_test test_repo_setup_suppresses_legacy_task_setup_fallback
  run_test test_task_setup_failure_reports_directory_and_command
  run_test test_repo_setup_failure_reports_directory_and_command
  run_test test_repo_setup_can_be_cleared_without_removing_other_repo_setup
  run_test test_interactive_init_writes_config_and_clones
  run_test test_interactive_init_can_add_first_task_after_cloning
  run_test test_interactive_init_persists_ide_when_terminal_prompt_eofs
  run_test test_interactive_init_does_not_prompt_for_task_branch_prefix
  run_test test_interactive_init_can_cancel_before_creating_project
  run_test test_interactive_init_can_create_project_in_custom_target_directory
  run_test test_interactive_init_accepts_slash_repo_base_branch
  run_test test_interactive_init_rejects_slash_in_main_worktrees_directory
  run_test test_interactive_init_eof_aborts_required_prompt
  run_test test_interactive_init_skips_tool_prompts_on_wsl
  run_test test_installer_downloads_cli_when_run_standalone
  run_test test_installer_standalone_uses_embedded_raw_base_url
  run_test test_installer_supports_pipe_to_bash
  run_test test_installer_pipe_to_bash_ignores_cwd_bin_workbranch
  run_test test_installer_installs_executable
  run_test test_installer_uses_custom_target_directory
  run_test test_installer_can_add_target_directory_to_zshrc

  log "Tests passed: $PASS"
  if [ "$FAIL" -ne 0 ]; then
    log "Tests failed: $FAIL"
    exit 1
  fi
}

# Detach stdin from any TTY so non-interactive tests see EOF (as in CI) instead
# of blocking on terminal input. Tests that need input pipe their own stdin.
main "$@" </dev/null
