task_state_dir_path() { printf '%s/%s/.workbranch' "$PROJECT_ROOT" "$1"; }

task_brief_path() { printf '%s/%s/TASK-WORKBRANCH.md' "$PROJECT_ROOT" "$1"; }

task_agents_path() { printf '%s/%s/AGENTS.md' "$PROJECT_ROOT" "$1"; }

task_noti_path() { printf '%s/%s/notifications.jsonl' "$(task_state_dir_path "$1")"; }

task_brief_title() {
  local file line
  file=$(task_brief_path "$1")
  [ -f "$file" ] || return 0
  while IFS= read -r line || [ -n "$line" ]; do
    [ -n "$line" ] || continue
    printf '%s' "$line" | sed 's/^#\{1,\}[[:space:]]*//'
    return 0
  done < "$file"
}

write_default_task_brief() {
  local task file
  task=$1
  file=$(task_brief_path "$task")
  [ -e "$file" ] && return 0
  cat > "$file" <<EOF_BRIEF
# $task

## Current work
- Update this task brief as work progresses.

## Notes
-
EOF_BRIEF
}

write_task_agent_guidance() {
  local task file
  task=$1
  file=$(task_agents_path "$task")
  [ -e "$file" ] && return 0
  cat > "$file" <<'EOF_GUIDANCE'
# Workbranch Task Guidance

This file is generated by workbranch for this task workspace.

- Keep the task brief current as work progresses.
- If your current working directory is the task root, update `TASK-WORKBRANCH.md`.
- If your current working directory is a repo folder under this task, update `../TASK-WORKBRANCH.md`.
- Use the task brief for human-readable current work, blockers, and next actions.
- Do not create repo-local task-state files unless the user explicitly asks.
EOF_GUIDANCE
}

write_default_task_state() {
  local task
  task=$1
  write_default_task_brief "$task" || die "failed to write task brief: $task"
  write_task_agent_guidance "$task" || die "failed to write task agent guidance: $task"
}

remove_task_state_files() {
  local task brief agents noti state_dir
  task=$1
  brief=$(task_brief_path "$task")
  agents=$(task_agents_path "$task")
  noti=$(task_noti_path "$task")
  state_dir=$(task_state_dir_path "$task")
  [ ! -f "$brief" ] || rm -f "$brief" || die "failed to remove task brief: $brief"
  [ ! -f "$agents" ] || rm -f "$agents" || die "failed to remove task agent guidance: $agents"
  [ ! -f "$noti" ] || rm -f "$noti" || die "failed to remove task notifications: $noti"
  rmdir "$state_dir" 2>/dev/null || true
}

resolve_current_task_from_cwd() {
  local dir parent task
  dir=$(pwd -P)
  while [ "$dir" != "$PROJECT_ROOT" ] && [ "$dir" != "/" ]; do
    parent=$(dirname "$dir")
    if [ "$parent" = "$PROJECT_ROOT" ]; then
      task=${dir##*/}
      is_task_workspace_path "$PROJECT_ROOT/$task" || return 1
      printf '%s' "$task"
      return 0
    fi
    dir=$parent
  done
  return 1
}

require_known_task_workspace() {
  local operation task task_dir
  operation=$1
  task=$2
  validate_task_folder_name "$task"
  task_dir="$PROJECT_ROOT/$task"
  if ! is_task_workspace_path "$task_dir"; then
    die "Cannot $operation: unknown task '$task'"
  fi
}

json_string() {
  printf '"'
  printf '%s' "$1" | json_escape
  printf '"'
}

json_escape() {
  awk 'BEGIN { ORS="" }
    {
      if (NR > 1) printf "\\n"
      line = $0
      gsub(/\\/, "\\\\", line)
      gsub(/"/, "\\\"", line)
      gsub(/\t/, "\\t", line)
      gsub(/\r/, "\\r", line)
      printf "%s", line
    }'
}

json_unescape() {
  awk '{
    out = ""
    for (i = 1; i <= length($0); i++) {
      c = substr($0, i, 1)
      if (c == "\\") {
        i++
        e = substr($0, i, 1)
        if (e == "n") out = out "\n"
        else if (e == "t") out = out "\t"
        else if (e == "r") out = out "\r"
        else out = out e
      } else {
        out = out c
      }
    }
    print out
  }'
}

noti_count() {
  local file count
  file=$(task_noti_path "$1")
  [ -f "$file" ] || { printf '0'; return 0; }
  count=$(wc -l < "$file" | tr -d '[:space:]')
  printf '%s' "${count:-0}"
}
