#!/usr/bin/env bash
set -eu

repo_root=$(cd "$(dirname "$0")/.." && pwd -P)
manifest=${WORKBRANCH_SOURCE_MANIFEST:-"$repo_root/scripts/workbranch-sources.txt"}
out=${1:-"$repo_root/bin/workbranch"}
tmp="$out.tmp.$$"
version=${WORKBRANCH_VERSION:-}
if [ -z "$version" ] && [ -f "$repo_root/.release-please-manifest.json" ]; then
  version=$(sed -n 's/.*"[.]": *"\([^"]*\)".*/\1/p' "$repo_root/.release-please-manifest.json" | head -n 1)
fi
version=${version:-"0.0.0-dev"}

cleanup() {
  rm -f "$tmp"
}
trap cleanup EXIT INT TERM

{
  printf '#!/usr/bin/env bash\n'
  printf '# Generated by scripts/build-workbranch.sh; edit src/workbranch/** instead.\n'
  printf '# shellcheck shell=bash\n'
  printf 'WORKBRANCH_VERSION=%q # x-release-please-version\n' "$version"
  while IFS= read -r source_path || [ -n "$source_path" ]; do
    case "$source_path" in
      ''|'#'*) continue ;;
    esac
    full_path="$repo_root/$source_path"
    [ -f "$full_path" ] || {
      printf 'missing source file: %s\n' "$source_path" >&2
      exit 1
    }
    printf '\n# ----- %s -----\n' "$source_path"
    sed '1{/^#!/d;}' "$full_path"
  done < "$manifest"
} > "$tmp"

/bin/bash -n "$tmp"
mv "$tmp" "$out"
chmod +x "$out"
trap - EXIT INT TERM
