use serde_json::json;
use workbranch_agent_runtime::{event, migration, store};

#[test]
fn correlated_waits_do_not_resume_on_another_tools_completion() {
    let mut db = store::open_memory().unwrap();
    let send = |db: &mut rusqlite::Connection, hook: &str, id: &str, tool: &str, at| {
        event::ingest(db, "/project/task", "claude", &json!({"session_id":"s", "hook_event_name":hook,"tool_use_id":id,"tool_name":tool,"tool_input":{"command":tool}}), at).unwrap();
    };
    send(&mut db, "PreToolUse", "a", "Bash", 1);
    send(&mut db, "PreToolUse", "b", "AskUserQuestion", 2);
    send(&mut db, "PostToolUse", "a", "Bash", 3);
    assert_eq!(store::snapshot(&db, 3).unwrap()[0].state, "waiting");
    send(&mut db, "PostToolUse", "b", "AskUserQuestion", 4);
    assert_eq!(store::snapshot(&db, 4).unwrap()[0].state, "running");
}

#[test]
fn latest_only_and_stale_is_not_idle() {
    let mut db = store::open_memory().unwrap();
    for prompt in ["old private request", "new request"] {
        event::ingest(&mut db,"/p/t","codex",&json!({"session_id":"s","turn_id":"t","hook_event_name":"UserPromptSubmit","prompt":prompt}), 10).unwrap();
    }
    let state = store::snapshot(&db, 911).unwrap();
    assert_eq!(state[0].prompt, "new request");
    assert_eq!(state[0].state, "running");
    assert_eq!(state[0].observation, "stale");
    assert!(
        !serde_json::to_string(&state)
            .unwrap()
            .contains("old private")
    );
}

#[test]
fn retired_turn_and_finished_tool_cannot_resurrect_session() {
    let mut db = store::open_memory().unwrap();
    for (hook, turn) in [
        ("UserPromptSubmit", "one"),
        ("Stop", "one"),
        ("UserPromptSubmit", "two"),
        ("PostToolUse", "one"),
    ] {
        event::ingest(&mut db,"/p/t","codex",&json!({"session_id":"s","turn_id":turn,"hook_event_name":hook,"tool_use_id":"late","tool_name":"Bash"}),10).unwrap();
    }
    let state = store::snapshot(&db, 10).unwrap();
    assert_eq!(state[0].turn_id, "two");
    assert_eq!(state[0].state, "running");
}

#[test]
fn migration_removes_legacy_and_preserves_other_instructions() {
    let root = tempfile::tempdir().unwrap();
    std::fs::write(root.path().join("TASK-WORKBRANCH.md"), "private old plan").unwrap();
    std::fs::write(root.path().join("AGENTS.md"),"<!-- nodeterm:start -->\nkeep me\n<!-- nodeterm:end -->\n# Workbranch Task Guidance\n\nThis file is generated by workbranch for this task workspace.\n\n- Keep the task brief current as work progresses.\n- Before editing a repo, read and follow repo-local agent instructions.\n\n## Custom rules\n- Always test\n").unwrap();
    let paths = vec![root.path().to_path_buf()];
    let preview = migration::run(&paths, false).unwrap();
    assert!(preview.pending > 0);
    assert!(root.path().join("TASK-WORKBRANCH.md").exists());
    migration::run(&paths, true).unwrap();
    assert!(!root.path().join("TASK-WORKBRANCH.md").exists());
    let guidance = std::fs::read_to_string(root.path().join("AGENTS.md")).unwrap();
    assert!(guidance.contains("keep me"));
    assert!(guidance.contains("Always test"));
    assert!(guidance.contains("repo-local"));
    assert!(!guidance.contains("task brief current"));
    assert_eq!(migration::run(&paths, true).unwrap().pending, 0);
}

#[test]
fn ambiguous_permission_is_not_resumed_by_unrelated_completion() {
    let mut db = store::open_memory().unwrap();
    for (event, id) in [("PermissionRequest", ""), ("PostToolUse", "other")] {
        event::ingest(&mut db,"/p/t","claude",&json!({"session_id":"s","hook_event_name":event,"tool_use_id":id,"tool_name":"Bash","tool_input":{"command":"deploy"}}),20).unwrap();
    }
    let rows = store::snapshot(&db, 20).unwrap();
    assert_eq!(rows[0].state, "waiting");
    assert_eq!(rows[0].observation, "uncertain");
}

#[test]
fn concurrent_sessions_do_not_lose_updates() {
    let root = tempfile::tempdir().unwrap();
    let path = root.path().join("runtime/state.sqlite3");
    store::open(&path).unwrap();
    let threads:Vec<_>=(0..8).map(|id|{let path=path.clone();std::thread::spawn(move||{
        let mut db=store::open(&path).unwrap();
        event::ingest(&mut db,"/p/t","claude",&json!({"session_id":format!("s{id}"),"hook_event_name":"UserPromptSubmit","prompt":"safe request"}),100).unwrap();
    })}).collect();
    for thread in threads {
        thread.join().unwrap();
    }
    assert_eq!(
        store::snapshot(&store::open(&path).unwrap(), 100)
            .unwrap()
            .len(),
        8
    );
}

#[test]
fn migration_refuses_symlinked_archive_and_preserves_runtime() {
    let root = tempfile::tempdir().unwrap();
    let outside = tempfile::tempdir().unwrap();
    std::fs::create_dir_all(root.path().join(".workbranch")).unwrap();
    std::fs::write(outside.path().join("keep"), "keep").unwrap();
    #[cfg(unix)]
    std::os::unix::fs::symlink(outside.path(), root.path().join(".workbranch/plans")).unwrap();
    std::fs::create_dir(outside.path().join("done")).unwrap();
    let report = migration::run(&[root.path().into()], true).unwrap();
    assert!(!report.errors.is_empty());
    assert!(outside.path().join("keep").exists());
}

#[test]
fn content_is_bounded_and_does_not_store_tool_output() {
    // Generated non-credential sentinel: verify omission without embedding a CLI secret.
    let synthetic_value = "redaction-test-only".repeat(2);
    let command = format!("curl --token {synthetic_value} https://example.invalid");
    let mut db = store::open_memory().unwrap();
    event::ingest(&mut db,"/p/t","claude",&json!({"session_id":"s","hook_event_name":"PreToolUse","tool_name":"Bash","tool_use_id":"a","tool_input":{"command":command},"tool_response":"do not store me"}),1).unwrap();
    let serialized = serde_json::to_string(&store::snapshot(&db, 1).unwrap()).unwrap();
    assert!(!serialized.contains(&synthetic_value));
    assert!(!serialized.contains("do not store me"));
}

#[test]
fn quoted_authorization_header_does_not_leak_bearer_value() {
    // Generated non-credential sentinel: verify omission without embedding a CLI secret.
    let synthetic_value = "redaction-test-only".repeat(2);
    let command = format!("curl -H \"Authorization: Bearer {synthetic_value}\" https://example.invalid");
    let mut db = store::open_memory().unwrap();
    event::ingest(&mut db,"/p/t","claude",&json!({"session_id":"s","hook_event_name":"PreToolUse","tool_name":"Bash","tool_use_id":"a","tool_input":{"command":command}}),1).unwrap();
    assert!(
        !serde_json::to_string(&store::snapshot(&db, 1).unwrap())
            .unwrap()
            .contains(&synthetic_value)
    );
}

#[test]
fn terminal_turn_and_completed_tool_wait_are_not_resurrected() {
    let mut db = store::open_memory().unwrap();
    for (hook, id) in [
        ("UserPromptSubmit", ""),
        ("PreToolUse", "a"),
        ("PostToolUse", "a"),
        ("PermissionRequest", "a"),
        ("Stop", ""),
        ("PreToolUse", "late"),
    ] {
        event::ingest(&mut db,"/p/t","codex",&json!({"session_id":"s","turn_id":"one","hook_event_name":hook,"tool_use_id":id,"tool_name":"Bash"}),1).unwrap();
        if hook == "PermissionRequest" {
            assert_eq!(store::snapshot(&db, 1).unwrap()[0].state, "running");
        }
    }
    assert_eq!(store::snapshot(&db, 1).unwrap()[0].state, "finished");
}

#[test]
fn recreated_workspace_does_not_inherit_prior_sessions() {
    let root = tempfile::tempdir().unwrap();
    let path = root.path().join("task");
    std::fs::create_dir(&path).unwrap();
    let marker = path.join(".workbranch.task");
    std::fs::write(&marker, "old").unwrap();
    let mut db = store::open_memory().unwrap();
    event::ingest(&mut db,path.to_str().unwrap(),"claude",&json!({"session_id":"s","hook_event_name":"UserPromptSubmit","prompt":"old workspace request"}),100).unwrap();
    // Keep old inode alive to prevent immediate inode reuse in the fixture.
    std::fs::rename(&marker, root.path().join("old-marker")).unwrap();
    std::fs::write(&marker, "new").unwrap();
    assert!(store::snapshot(&db, 100).unwrap().is_empty());
}

#[test]
fn custom_guidance_with_legacy_words_is_not_removed() {
    let root = tempfile::tempdir().unwrap();
    let p = root.path().join("AGENTS.md");
    std::fs::write(&p,"# Workbranch Task Guidance\nThis file is generated by workbranch for this task workspace.\n- Keep the task brief current as work progresses.\n## Custom deployment rules\n- Keep TASK-WORKBRANCH.md examples in fixtures.\n").unwrap();
    migration::run(&[root.path().into()], true).unwrap();
    let text = std::fs::read_to_string(p).unwrap();
    assert!(text.contains("Keep TASK-WORKBRANCH.md examples"));
    assert!(!text.contains("task brief current"));
}

#[test]
fn session_end_blocks_late_tools_until_a_new_prompt() {
    let mut db = store::open_memory().unwrap();
    for event in ["UserPromptSubmit", "Stop", "SessionEnd", "PreToolUse"] {
        event::ingest(&mut db,"/p/t","claude",&json!({"session_id":"s","hook_event_name":event,"tool_use_id":"late","tool_name":"Bash"}),1).unwrap();
    }
    assert_eq!(store::snapshot(&db, 1).unwrap()[0].state, "idle");
    event::ingest(
        &mut db,
        "/p/t",
        "claude",
        &json!({"session_id":"s","hook_event_name":"UserPromptSubmit","prompt":"new"}),
        2,
    )
    .unwrap();
    assert_eq!(store::snapshot(&db, 2).unwrap()[0].state, "running");
}

#[test]
fn home_legacy_storage_is_cleaned_without_touching_new_runtime() {
    let tmp = tempfile::tempdir().unwrap();
    let root = tmp.path().join(".workbranch");
    std::fs::create_dir_all(root.join("runtime")).unwrap();
    std::fs::write(root.join("agent.jsonl"), "legacy").unwrap();
    std::fs::write(root.join("runtime/state.sqlite3"), "new runtime").unwrap();
    let result = migration::run(std::slice::from_ref(&root), true).unwrap();
    assert!(result.errors.is_empty());
    assert!(!root.join("agent.jsonl").exists());
    assert_eq!(
        std::fs::read_to_string(root.join("runtime/state.sqlite3")).unwrap(),
        "new runtime"
    );
}

#[test]
fn fenced_guidance_example_is_not_migrated() {
    let tmp = tempfile::tempdir().unwrap();
    let path = tmp.path().join("AGENTS.md");
    let source = "# My rules\n```markdown\n# Workbranch Task Guidance\nThis file is generated by workbranch for this task workspace.\n- Keep the task brief current as work progresses.\n```\n";
    std::fs::write(&path, source).unwrap();
    assert_eq!(
        migration::run(&[tmp.path().into()], true).unwrap().pending,
        0
    );
    assert_eq!(std::fs::read_to_string(path).unwrap(), source);
}

#[test]
fn command_arrays_and_question_text_are_available_as_activity() {
    let mut db = store::open_memory().unwrap();
    event::ingest(&mut db,"/p/t","codex",&json!({"session_id":"s","hook_event_name":"PreToolUse","tool_name":"Bash","tool_use_id":"a","tool_input":{"command":["bash","-lc","pnpm test"]}}),1).unwrap();
    assert!(
        store::snapshot(&db, 1).unwrap()[0]
            .activity
            .contains("pnpm test")
    );
    event::ingest(&mut db,"/p/t","codex",&json!({"session_id":"s","hook_event_name":"PreToolUse","tool_name":"request_user_input","tool_use_id":"b","tool_input":{"questions":[{"question":"Deploy to staging?"}]}}),2).unwrap();
    assert!(
        store::snapshot(&db, 2).unwrap()[0]
            .activity
            .contains("Deploy to staging?")
    );
}

#[test]
fn grok_camel_case_payloads_are_normalized_and_not_recorded_as_claude() {
    let mut db = store::open_memory().unwrap();
    let prompt = json!({"sessionId":"g","hookEventName":"user_prompt_submit","hook_event_name":"UserPromptSubmit","cwd":"/p/t","workspaceRoot":"/p/t","promptId":"turn","prompt":"Fix the UI"});
    assert!(event::ingest(&mut db, "/p/t", "claude", &prompt, 10).is_err());
    event::ingest(&mut db, "/p/t", "grok", &prompt, 10).unwrap();
    event::ingest(&mut db,"/p/t","grok",&json!({"sessionId":"g","hookEventName":"pre_tool_use","promptId":"turn","toolName":"run_terminal_command","toolUseId":"tool","toolInput":{"command":"pnpm test"}}),11).unwrap();
    let state = store::snapshot(&db, 11).unwrap();
    assert_eq!(state.len(), 1);
    assert_eq!(state[0].provider, "grok");
    assert!(state[0].activity.contains("pnpm test"));
    event::ingest(
        &mut db,
        "/p/t",
        "grok",
        &json!({"sessionId":"g","hookEventName":"stop_cancelled","promptId":"turn"}),
        12,
    )
    .unwrap();
    assert_eq!(store::snapshot(&db, 12).unwrap()[0].outcome, "interrupted");
}

#[test]
fn grok_stop_is_tentative_until_idle_and_can_continue_tools() {
    let mut db = store::open_memory().unwrap();
    let send = |db: &mut rusqlite::Connection, event: &str, notification: &str| {
        event::ingest(db,"/p/t","grok",&json!({"sessionId":"g","promptId":"p","hookEventName":event,"notificationType":notification,"toolUseId":"new","toolName":"read_file"}),100).unwrap()
    };
    send(&mut db, "user_prompt_submit", "");
    send(&mut db, "stop", "");
    assert_eq!(
        store::snapshot(&db, 100).unwrap()[0].observation,
        "uncertain"
    );
    send(&mut db, "pre_tool_use", "");
    assert_eq!(store::snapshot(&db, 100).unwrap()[0].state, "running");
    send(&mut db, "stop", "");
    send(&mut db, "notification", "idle_prompt");
    assert_eq!(
        store::snapshot(&db, 100).unwrap()[0].observation,
        "observed"
    );
}

#[test]
fn registered_hook_collector_works_outside_path() {
    let temp = tempfile::tempdir().unwrap();
    let binary = std::path::Path::new(env!("CARGO_BIN_EXE_workbranch-agent-runtime"));
    let result = std::process::Command::new(binary)
        .arg("register")
        .arg(binary)
        .env("WORKBRANCH_RUNTIME_DIR", temp.path())
        .output()
        .unwrap();
    assert!(
        result.status.success(),
        "{}",
        String::from_utf8_lossy(&result.stderr)
    );
    let result = std::process::Command::new(temp.path().join("hook-collector"))
        .arg("version")
        .output()
        .unwrap();
    assert!(result.status.success());
}
