set -u

PROGRAM=${0##*/}
PROJECT_ROOT=""
CONFIG_FILE=""
PROJECT_NAME=""
BASE_DIR=""
BRANCH_PREFIX=""
TASK_SETUP=""
REPO_NAMES=()
REPO_URLS=()
REPO_BASE_BRANCHES=()
CREATED_PATHS=()
CREATED_WORKTREES=()
CREATED_WORKTREE_BASES=()
CREATED_BRANCH_REPOS=()
CREATED_BRANCH_NAMES=()
PREFLIGHT_ERRORS=()
FILTER_REPO=""
ARGS=()
