use crate::Result;
use serde::Serialize;
use std::{
    fs,
    path::{Path, PathBuf},
};

#[derive(Serialize, Default)]
#[serde(rename_all = "camelCase")]
pub struct Report {
    pub schema_version: u32,
    pub pending: usize,
    pub applied: usize,
    pub actions: Vec<Action>,
    pub errors: Vec<String>,
}
#[derive(Serialize)]
pub struct Action {
    pub path: String,
    pub kind: String,
}
fn safe_path(root: &Path, path: &Path) -> bool {
    let Ok(relative) = path.strip_prefix(root) else {
        return false;
    };
    let mut current = root.to_path_buf();
    for part in relative.components() {
        current.push(part);
        if current.is_symlink() {
            return false;
        }
    }
    true
}
const LEGACY_LINES: &[&str] = &[
    "- 현재 작업 디렉터리가 task root이면 `TASK-WORKBRANCH.md`를 갱신합니다.",
    "- 현재 작업 디렉터리가 이 task 아래의 repo folder이면 `../TASK-WORKBRANCH.md`를 갱신합니다.",
    "- task brief의 H1 바로 아래 `status:`를 현재 작업 단계의 source of truth로 유지합니다.",
    "- 완료된 현재 Plan은 `workbranch done <task>` 또는 land/finalize/pull archive 프롬프트로 `.workbranch/plans/done/`에 보관합니다.",
    "- 사용자가 명시적으로 요청하지 않는 한 repo-local task-state file을 만들지 않습니다.",
    "- 작업 단계가 바뀔 때만 `status:` 한 줄을 갱신합니다.",
    "- 기본 단계 흐름은 todo → planning → in-progress → review → done 입니다.",
    "- 계획을 포함한 의미 있는 작업을 시작하면 `status:`를 `todo`에서 `planning`으로 즉시 변경합니다.",
    "- `blocked`는 `in-progress`에서만 사용하고, blocker가 해소되면 `in-progress`로 복원합니다.",
    "- `status:` 바로 아래에 지금 하는 일을 나타내는 요약 한 줄을 유지하고, 작업 내용이 바뀌면 갱신합니다.",
    "- 사용자가 명시적으로 요청한 경우에만 checklist나 note를 추가합니다.",
    "- 추가 본문은 `.workbranch.config`의 `PREFERRED_LANGUAGE` 설정 언어로 작성합니다.",
    "- Keep the task brief current as work progresses.",
    "- If your current working directory is the task root, update `TASK-WORKBRANCH.md`.",
    "- If your current working directory is a repo folder under this task, update `../TASK-WORKBRANCH.md`.",
    "- Keep the `status:` line immediately below the task brief H1 as the source of truth for the current stage.",
    "- Archive the completed current Plan with `workbranch done <task>` or the land/finalize/pull archive prompt; archives live under `.workbranch/plans/done/`.",
    "- Do not create repo-local task-state files unless the user explicitly asks.",
    "- Update only the `status:` line when the task stage changes.",
    "- The normal stage flow is todo → planning → in-progress → review → done.",
    "- When meaningful work starts, including planning, move `status:` from `todo` to `planning` immediately.",
    "- Use `blocked` only from `in-progress`; when unblocked, restore `in-progress`.",
    "- Keep a one-line summary of the current work directly below `status:`, and refresh it when the focus changes.",
    "- Add checklists or notes only when the user explicitly requests them.",
    "- Write any additional body content in the language set by `PREFERRED_LANGUAGE` in `.workbranch.config`.",
];

fn clean_guidance(text: &str) -> String {
    if !text.contains("This file is generated by workbranch")
        && !text.contains("이 파일은 workbranch가")
    {
        return text.into();
    }
    let mut lines = Vec::new();
    let mut generated = false;
    let mut fenced = false;
    for line in text.lines() {
        if line.trim_start().starts_with("```") || line.trim_start().starts_with("~~~") {
            fenced = !fenced;
            lines.push(line);
            continue;
        }
        if fenced {
            lines.push(line);
            continue;
        }
        if line == "# Workbranch Task Guidance" || line == "# Workbranch 작업 안내" {
            generated = true;
        } else if line.starts_with("# ") {
            generated = false;
        }
        if generated
            && (line == "## Task progress update protocol" || line == "## 작업 진행 업데이트 규칙")
        {
            continue;
        } else if line.starts_with("## ") {
            generated = false;
        }
        if generated {
            if line.starts_with("- Make code changes and run Git commands inside the repo folders;")
            {
                lines.push("- Make code changes and run Git commands inside the repo folders.");
                continue;
            }
            if line.starts_with("- 코드 변경과 Git 명령은 repo folder 안에서 수행하고,")
            {
                lines.push("- 코드 변경과 Git 명령은 repo folder 안에서 수행합니다.");
                continue;
            }
            if LEGACY_LINES.contains(&line) {
                continue;
            }
        }
        lines.push(line);
    }
    format!("{}\n", lines.join("\n").trim_end())
}
pub fn run(workspaces: &[PathBuf], apply: bool) -> Result<Report> {
    let mut report = Report {
        schema_version: 1,
        ..Report::default()
    };
    for root in workspaces {
        if root.is_symlink() || !root.is_dir() {
            report
                .errors
                .push(format!("Invalid workspace: {}", root.display()));
            continue;
        }
        let legacy_paths: &[&str] = if root.file_name().is_some_and(|name| name == ".workbranch") {
            &[
                "plans/done",
                "agent.jsonl",
                "agent-waiting",
                "TASK-WORKBRANCH.md",
            ]
        } else {
            &[
                "TASK-WORKBRANCH.md",
                ".workbranch/plans/done",
                ".workbranch/agent.jsonl",
                ".workbranch/agent-waiting",
            ]
        };
        for relative in legacy_paths {
            let path = root.join(relative);
            if !path.exists() && !path.is_symlink() {
                continue;
            }
            if !safe_path(root, &path) {
                report
                    .errors
                    .push(format!("Refusing symbolic link: {}", path.display()));
                continue;
            }
            report.pending += 1;
            report.actions.push(Action {
                path: path.display().to_string(),
                kind: "delete-legacy".into(),
            });
            if apply {
                let result = if path.is_dir() {
                    fs::remove_dir_all(&path)
                } else {
                    fs::remove_file(&path)
                };
                match result {
                    Ok(()) => report.applied += 1,
                    Err(e) => report.errors.push(format!("{}: {e}", path.display())),
                }
            }
        }
        let path = root.join("AGENTS.md");
        if !path.exists() {
            continue;
        }
        if !safe_path(root, &path) {
            report
                .errors
                .push(format!("Refusing symbolic link: {}", path.display()));
            continue;
        }
        let source = match fs::read_to_string(&path) {
            Ok(s) => s,
            Err(e) => {
                report.errors.push(format!("{}: {e}", path.display()));
                continue;
            }
        };
        let cleaned = clean_guidance(&source);
        if source == cleaned {
            continue;
        }
        report.pending += 1;
        report.actions.push(Action {
            path: path.display().to_string(),
            kind: "remove-legacy-guidance".into(),
        });
        if apply {
            let tmp =
                path.with_file_name(format!(".workbranch-guidance-{}.tmp", std::process::id()));
            let result = (|| -> Result<()> {
                use std::io::Write;
                let mut out = fs::OpenOptions::new()
                    .write(true)
                    .create_new(true)
                    .open(&tmp)?;
                fs::set_permissions(&tmp, fs::metadata(&path)?.permissions())?;
                out.write_all(cleaned.as_bytes())?;
                out.sync_all()?;
                if fs::read_to_string(&path)? != source {
                    return Err("Guidance changed during migration; retry".into());
                }
                fs::rename(&tmp, &path)?;
                Ok(())
            })();
            match result {
                Ok(()) => report.applied += 1,
                Err(e) => {
                    let _ = fs::remove_file(&tmp);
                    report.errors.push(format!("{}: {e}", path.display()));
                }
            }
        }
    }
    Ok(report)
}
